# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robot_manager/robot_speaker.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class robot_speaker(genpy.Message):
  _md5sum = "40c45f84b5c08c0a75df65acb133f8c5"
  _type = "robot_manager/robot_speaker"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string chinese_text
int32 msg_buffer_flag
int32 msg_clear_buffer_flag
"""
  __slots__ = ['chinese_text','msg_buffer_flag','msg_clear_buffer_flag']
  _slot_types = ['string','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       chinese_text,msg_buffer_flag,msg_clear_buffer_flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(robot_speaker, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.chinese_text is None:
        self.chinese_text = ''
      if self.msg_buffer_flag is None:
        self.msg_buffer_flag = 0
      if self.msg_clear_buffer_flag is None:
        self.msg_clear_buffer_flag = 0
    else:
      self.chinese_text = ''
      self.msg_buffer_flag = 0
      self.msg_clear_buffer_flag = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.chinese_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.msg_buffer_flag, _x.msg_clear_buffer_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.chinese_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.chinese_text = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg_buffer_flag, _x.msg_clear_buffer_flag,) = _get_struct_2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.chinese_text
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2i().pack(_x.msg_buffer_flag, _x.msg_clear_buffer_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.chinese_text = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.chinese_text = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.msg_buffer_flag, _x.msg_clear_buffer_flag,) = _get_struct_2i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
