// Generated by gencpp from file robot_manager/robot_state.msg
// DO NOT EDIT!


#ifndef ROBOT_MANAGER_MESSAGE_ROBOT_STATE_H
#define ROBOT_MANAGER_MESSAGE_ROBOT_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_manager
{
template <class ContainerAllocator>
struct robot_state_
{
  typedef robot_state_<ContainerAllocator> Type;

  robot_state_()
    : robot_electricity(0.0)
    , robot_state(0)
    , robot_driver_state(0)
    , robot_camera_state(0)  {
    }
  robot_state_(const ContainerAllocator& _alloc)
    : robot_electricity(0.0)
    , robot_state(0)
    , robot_driver_state(0)
    , robot_camera_state(0)  {
  (void)_alloc;
    }



   typedef float _robot_electricity_type;
  _robot_electricity_type robot_electricity;

   typedef int32_t _robot_state_type;
  _robot_state_type robot_state;

   typedef int32_t _robot_driver_state_type;
  _robot_driver_state_type robot_driver_state;

   typedef int32_t _robot_camera_state_type;
  _robot_camera_state_type robot_camera_state;





  typedef boost::shared_ptr< ::robot_manager::robot_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_manager::robot_state_<ContainerAllocator> const> ConstPtr;

}; // struct robot_state_

typedef ::robot_manager::robot_state_<std::allocator<void> > robot_state;

typedef boost::shared_ptr< ::robot_manager::robot_state > robot_statePtr;
typedef boost::shared_ptr< ::robot_manager::robot_state const> robot_stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_manager::robot_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_manager::robot_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_manager::robot_state_<ContainerAllocator1> & lhs, const ::robot_manager::robot_state_<ContainerAllocator2> & rhs)
{
  return lhs.robot_electricity == rhs.robot_electricity &&
    lhs.robot_state == rhs.robot_state &&
    lhs.robot_driver_state == rhs.robot_driver_state &&
    lhs.robot_camera_state == rhs.robot_camera_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_manager::robot_state_<ContainerAllocator1> & lhs, const ::robot_manager::robot_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_manager::robot_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_manager::robot_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_manager::robot_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_manager::robot_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_manager::robot_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_manager::robot_state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_manager::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5bad53ba22220257c1d7f0639451f8f3";
  }

  static const char* value(const ::robot_manager::robot_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5bad53ba22220257ULL;
  static const uint64_t static_value2 = 0xc1d7f0639451f8f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_manager::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_manager/robot_state";
  }

  static const char* value(const ::robot_manager::robot_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_manager::robot_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 robot_electricity\n"
"int32 robot_state\n"
"int32 robot_driver_state\n"
"int32 robot_camera_state\n"
"\n"
"\n"
;
  }

  static const char* value(const ::robot_manager::robot_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_manager::robot_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_electricity);
      stream.next(m.robot_state);
      stream.next(m.robot_driver_state);
      stream.next(m.robot_camera_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_manager::robot_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_manager::robot_state_<ContainerAllocator>& v)
  {
    s << indent << "robot_electricity: ";
    Printer<float>::stream(s, indent + "  ", v.robot_electricity);
    s << indent << "robot_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_state);
    s << indent << "robot_driver_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_driver_state);
    s << indent << "robot_camera_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_camera_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MANAGER_MESSAGE_ROBOT_STATE_H
