// Generated by gencpp from file robot_manager/robot_control.msg
// DO NOT EDIT!


#ifndef ROBOT_MANAGER_MESSAGE_ROBOT_CONTROL_H
#define ROBOT_MANAGER_MESSAGE_ROBOT_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_manager
{
template <class ContainerAllocator>
struct robot_control_
{
  typedef robot_control_<ContainerAllocator> Type;

  robot_control_()
    : robot_control_date(0)
    , robot_speed(0)  {
    }
  robot_control_(const ContainerAllocator& _alloc)
    : robot_control_date(0)
    , robot_speed(0)  {
  (void)_alloc;
    }



   typedef int32_t _robot_control_date_type;
  _robot_control_date_type robot_control_date;

   typedef int32_t _robot_speed_type;
  _robot_speed_type robot_speed;





  typedef boost::shared_ptr< ::robot_manager::robot_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_manager::robot_control_<ContainerAllocator> const> ConstPtr;

}; // struct robot_control_

typedef ::robot_manager::robot_control_<std::allocator<void> > robot_control;

typedef boost::shared_ptr< ::robot_manager::robot_control > robot_controlPtr;
typedef boost::shared_ptr< ::robot_manager::robot_control const> robot_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_manager::robot_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_manager::robot_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_manager::robot_control_<ContainerAllocator1> & lhs, const ::robot_manager::robot_control_<ContainerAllocator2> & rhs)
{
  return lhs.robot_control_date == rhs.robot_control_date &&
    lhs.robot_speed == rhs.robot_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_manager::robot_control_<ContainerAllocator1> & lhs, const ::robot_manager::robot_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_manager::robot_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_manager::robot_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_manager::robot_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_manager::robot_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_manager::robot_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_manager::robot_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_manager::robot_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfb01f34da152f6ce58d56cb22596b17";
  }

  static const char* value(const ::robot_manager::robot_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfb01f34da152f6cULL;
  static const uint64_t static_value2 = 0xe58d56cb22596b17ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_manager::robot_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_manager/robot_control";
  }

  static const char* value(const ::robot_manager::robot_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_manager::robot_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 robot_control_date\n"
"int32 robot_speed\n"
;
  }

  static const char* value(const ::robot_manager::robot_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_manager::robot_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_control_date);
      stream.next(m.robot_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_manager::robot_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_manager::robot_control_<ContainerAllocator>& v)
  {
    s << indent << "robot_control_date: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_control_date);
    s << indent << "robot_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MANAGER_MESSAGE_ROBOT_CONTROL_H
